name: "my-app-test"

services:

  web:
    container_name: my-app-web-test-dev
    build: ./web
    command: sh -c "npm run prisma:migrate:deploy && npm run prisma:generate && npm run prisma:seed && npm run dev"
    ports:
      - 3000:3000
    env_file: .env.e2e.local
    networks:
      - my-app-test-network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: 'curl --fail http://localhost:3000 || exit 1'
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s

  database:
    container_name: my-app-database-test
    image: postgres:16
    env_file: .env.e2e.local
    restart: always
    ports:
      - 5432:5432
    networks:
      - my-app-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  my-app-test-network:
    driver: bridge