name: Unit Test web

on:
  push:
    paths:
      - 'web/**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        working-directory: web
        
      - name: Unit tests
        run: npm run test
        working-directory: web