FROM mcr.microsoft.com/playwright:v1.53.1-jammy
WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    build-essential \
    sqlite3 \
    libsqlite3-dev
    
COPY . .
RUN npm i
CMD ["npm", "run", "test:e2e"]